#!/usr/bin/env node
import crypto from "crypto";
import fs from "fs/promises";
import https from "https";
import path from "path";
import { fileURLToPath } from "url";

const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const WEBFONTS_DIR = path.join(ROOT_DIR, "webfonts");
const STATIC_DIR = path.join(ROOT_DIR, "static");
const OUTPUT_CSS = path.join(STATIC_DIR, "fonts.css");
const FONT_CSS_URL =
  "https://fonts.googleapis.com/css2?family=Diphylleia:wght@400&family=Gothic+A1:wght@300;400;500;600;700&display=swap";
const USER_AGENT =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

function fetchUrl(url, responseType = "text") {
  return new Promise((resolve, reject) => {
    const request = https.get(
      url,
      {
        headers: {
          "User-Agent": USER_AGENT,
          Accept: responseType === "text" ? "text/css,*/*;q=0.1" : "*/*"
        }
      },
      (response) => {
        if (response.statusCode && response.statusCode >= 300 && response.statusCode < 400) {
          const location = response.headers.location;
          if (location) {
            response.resume();
            const redirectUrl = new URL(location, url).toString();
            resolve(fetchUrl(redirectUrl, responseType));
            return;
          }
        }

        if (response.statusCode !== 200) {
          response.resume();
          reject(new Error(`Request failed (${response.statusCode}) for ${url}`));
          return;
        }

        const chunks = [];
        response.on("data", (chunk) => chunks.push(chunk));
        response.on("end", () => {
          const buffer = Buffer.concat(chunks);
          resolve(responseType === "text" ? buffer.toString("utf8") : buffer);
        });
      }
    );

    request.on("error", reject);
  });
}

function extractFontUrls(cssText) {
  const urls = new Set();
  const urlPattern = /url\(([^)]+)\)/g;
  let match = null;
  while ((match = urlPattern.exec(cssText)) !== null) {
    const raw = match[1].trim().replace(/^['"]|['"]$/g, "");
    if (raw.startsWith("https://")) {
      urls.add(raw);
    }
  }
  return Array.from(urls);
}

function buildFileName(url) {
  const parsed = new URL(url);
  const baseName = path.basename(parsed.pathname);
  const hash = crypto.createHash("sha1").update(url).digest("hex").slice(0, 8);
  if (baseName.endsWith(".woff2")) {
    return `${baseName.replace(".woff2", "")}-${hash}.woff2`;
  }
  return `${baseName}-${hash}.woff2`;
}

async function main() {
  await fs.mkdir(WEBFONTS_DIR, { recursive: true });
  await fs.mkdir(STATIC_DIR, { recursive: true });

  const cssText = await fetchUrl(FONT_CSS_URL, "text");
  const fontUrls = extractFontUrls(cssText);
  const urlMap = new Map();

  for (const fontUrl of fontUrls) {
    const fileName = buildFileName(fontUrl);
    const filePath = path.join(WEBFONTS_DIR, fileName);
    const fileData = await fetchUrl(fontUrl, "buffer");
    await fs.writeFile(filePath, fileData);
    urlMap.set(fontUrl, `../webfonts/${fileName}`);
  }

  const urlPattern = /url\(([^)]+)\)/g;
  const localCss = cssText.replace(urlPattern, (fullMatch, rawValue) => {
    const cleaned = rawValue.trim().replace(/^['"]|['"]$/g, "");
    const localPath = urlMap.get(cleaned);
    return localPath ? `url("${localPath}")` : fullMatch;
  });

  const banner = "/* Generated by scripts/fetch-fonts.mjs. */\n";
  await fs.writeFile(OUTPUT_CSS, `${banner}${localCss}`);

  console.log(`Downloaded ${urlMap.size} font files.`);
  console.log(`Wrote ${OUTPUT_CSS}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
